// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hysios/mx/platform/config"
	"github.com/hysios/mx/platform/logger"
	"github.com/hysios/mx/platform/model"
	"github.com/hysios/mx/platform/policy"
	"github.com/hysios/mx/platform/server"
	"google.golang.org/grpc"
	"gorm.io/gorm"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func setupServer(addr string) (*grpc.Server, error) {
	configConfig, err := config.LoadDefault()
	if err != nil {
		return nil, err
	}
	loggerLogger := logger.ProviderLog()
	db, err := config.ProviderDatabase(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	enforcer, err := policy.EnforecerProvider(db, configConfig)
	if err != nil {
		return nil, err
	}
	grpcServer := server.BuildGPCServer(db, loggerLogger, enforcer)
	return grpcServer, nil
}

// wire.go:

func setupDB() {
	config.SetupDB(func(db *gorm.DB, logger2 *logger.Logger) error {
		log := logger2.Sugar()
		log.Infof("auto migrates database")

		if err := db.AutoMigrate(
			&model.User{},
			&model.Certificate{},
		); err != nil {
			log.Errorf("failed to migrate: %v", err)
			return err
		}
		model.AutoIncrementStart(db, &model.User{}, "id", 100000)

		_, err := model.CreateAdmin(db, "admin", "admin")
		return err
	})
}
